server:
  port: 8001
spring:
  #redis:
    #host: 172.16.163.55
    #port: 6379
    #password: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.163.55:3306/parking?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.wzwl.parking.model
  #configuration:
    #map-underscore-to-camel-case: false

